#include <stdio.h>
#include "../dep/vecta.h"
#include "./notebook/types.h"

enum SpColor
{
    SpColor_AliceBlue            = 0,
    SpColor_AntiqueWhite         = 1,
    SpColor_Aqua                 = 2,
    SpColor_Aquamarine           = 3,
    SpColor_Azure                = 4,
    SpColor_Beige                = 5,
    SpColor_Bisque               = 6,
    SpColor_Black                = 7,
    SpColor_BlanchedAlmond       = 8,
    SpColor_Blue                 = 9,
    SpColor_BlueViolet           = 10,
    SpColor_Brown                = 11,
    SpColor_BurlyWood            = 12,
    SpColor_CadetBlue            = 13,
    SpColor_Chartreuse           = 14,
    SpColor_Chocolate            = 15,
    SpColor_Coral                = 16,
    SpColor_CornflowerBlue       = 17,
    SpColor_CornSilk             = 18,
    SpColor_Crimson              = 19,
    SpColor_Cyan                 = 20,
    SpColor_DarkBlue             = 21,
    SpColor_DarkCyan             = 22,
    SpColor_DarkGoldenrod        = 23,
    SpColor_DarkGray             = 24,
    SpColor_DarkGreen            = 25,
    SpColor_DarkGrey             = 26,
    SpColor_DarkKhaki            = 27,
    SpColor_DarkMagenta          = 28,
    SpColor_DarkOliveGreen       = 29,
    SpColor_DarkOrange           = 30,
    SpColor_DarkOrchid           = 31,
    SpColor_DarkRed              = 32,
    SpColor_DarkSalmon           = 33,
    SpColor_DarkSeaGreen         = 34,
    SpColor_DarkSlateBlue        = 35,
    SpColor_DarkSlateGray        = 36,
    SpColor_DarkSlateGrey        = 37,
    SpColor_DarkTurquoise        = 38,
    SpColor_DarkViolet           = 39,
    SpColor_DeepPink             = 40,
    SpColor_DeepSkyBlue          = 41,
    SpColor_DimGray              = 42,
    SpColor_DimGrey              = 43,
    SpColor_DodgerBlue           = 44,
    SpColor_FireBrick            = 45,
    SpColor_FloralWhite          = 46,
    SpColor_ForestGreen          = 47,
    SpColor_Fuchsia              = 48,
    SpColor_Gainsboro            = 49,
    SpColor_GhostWhite           = 50,
    SpColor_Gold                 = 51,
    SpColor_Goldenrod            = 52,
    SpColor_Gray                 = 53,
    SpColor_Green                = 54,
    SpColor_GreenYellow          = 55,
    SpColor_Grey                 = 56,
    SpColor_Honeydew             = 57,
    SpColor_HotPink              = 58,
    SpColor_IndianRed            = 59,
    SpColor_Indigo               = 60,
    SpColor_Ivory                = 61,
    SpColor_Khaki                = 62,
    SpColor_Lavender             = 63,
    SpColor_LavenderBlush        = 64,
    SpColor_LawnGreen            = 65,
    SpColor_Lemonchiffon         = 66,
    SpColor_LightBlue            = 67,
    SpColor_LightCoral           = 68,
    SpColor_LightCyan            = 69,
    SpColor_LightGoldenrodYellow = 70,
    SpColor_LightGray            = 71,
    SpColor_LightGreen           = 72,
    SpColor_LightGrey            = 73,
    SpColor_LightPink            = 74,
    SpColor_LightSalmon          = 75,
    SpColor_LightSeaGreen        = 76,
    SpColor_LightSkyBlue         = 77,
    SpColor_LightSlateGray       = 78,
    SpColor_LightSlateGrey       = 79,
    SpColor_LightSteelBlue       = 80,
    SpColor_LightYellow          = 81,
    SpColor_Lime                 = 82,
    SpColor_LimeGreen            = 83,
    SpColor_Linen                = 84,
    SpColor_Magenta              = 85,
    SpColor_Maroon               = 86,
    SpColor_MediumAquamarine     = 87,
    SpColor_MediumBlue           = 88,
    SpColor_MediumOrchid         = 89,
    SpColor_MediumPurple         = 90,
    SpColor_MediumSeaGreen       = 91,
    SpColor_MediumSlateblue      = 92,
    SpColor_MediumSpringGreen    = 93,
    SpColor_MediumTurquoise      = 94,
    SpColor_MediumVioletRed      = 95,
    SpColor_MidnightBlue         = 96,
    SpColor_MintCream            = 97,
    SpColor_MistyRose            = 98,
    SpColor_Moccasin             = 99,
    SpColor_NavajoWhite          = 100,
    SpColor_Navy                 = 101,
    SpColor_OldLace              = 102,
    SpColor_Olive                = 103,
    SpColor_OliveDrab            = 104,
    SpColor_Orange               = 105,
    SpColor_OrangeRed            = 106,
    SpColor_Orchid               = 107,
    SpColor_PaleGoldenrod        = 108,
    SpColor_PaleGreen            = 109,
    SpColor_PaleTurquoise        = 110,
    SpColor_PaleVioletred        = 111,
    SpColor_PapayaWhip           = 112,
    SpColor_PeachPuff            = 113,
    SpColor_Peru                 = 114,
    SpColor_Pink                 = 115,
    SpColor_Plum                 = 116,
    SpColor_PowderBlue           = 117,
    SpColor_Purple               = 118,
    SpColor_Red                  = 119,
    SpColor_RosyBrown            = 120,
    SpColor_RoyalBlue            = 121,
    SpColor_SaddleBrown          = 122,
    SpColor_Salmon               = 123,
    SpColor_SandyBrown           = 124,
    SpColor_SeaGreen             = 125,
    SpColor_Seashell             = 126,
    SpColor_Sienna               = 127,
    SpColor_Silver               = 128,
    SpColor_SkyBlue              = 129,
    SpColor_SlateBlue            = 130,
    SpColor_SlateGray            = 131,
    SpColor_SlateGrey            = 132,
    SpColor_Snow                 = 133,
    SpColor_Springgreen          = 134,
    SpColor_SteelBlue            = 135,
    SpColor_Tan                  = 136,
    SpColor_Teal                 = 137,
    SpColor_Thistle              = 138,
    SpColor_Tomato               = 139,
    SpColor_Turquoise            = 140,
    SpColor_Violet               = 141,
    SpColor_Wheat                = 142,
    SpColor_White                = 143,
    SpColor_WhiteSmoke           = 144,
    SpColor_Yellow               = 145,
    SpColor_YellowGreen          = 146
};

static const char* SP_COLOR_STRINGS[] =
{
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkgrey",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "greenyellow",
    "grey",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgreen",
    "lightgrey",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen"
};


void Move(Point2D coordinate_center)
{
    printf("move %f %f\n", coordinate_center.x, coordinate_center.y);
}

void SetUnit(float unit)
{
    printf("unit %.2f\n", unit);
}

// TODO: Optimize to not print the color each time
// TODO: Optimize to not print the command each time
void PrintPoint(Point2D a, SpColor color)
{
    printf("colour %s\n", SP_COLOR_STRINGS[color]);
    printf("points\n");
    printf("%.2f %.2f\n", a.x, a.y);
}

void PrintLine(Point2D a, Point2D b, SpColor color, float width = 1)
{
    printf("colour %s\n", SP_COLOR_STRINGS[color]);
    printf("width %.2f\n", width);
    printf("lines\n");
    printf("%.2f %.2f %.2f %.f\n", a.x, a.y, b.x, b.y);
}
